### ISSUE TITLE
Class without a namespace - crash

### ISSUE THREAD

**Issue by digitalcosmos** [Geaz/sharpDox#32]
Document fails to build if there's a class that doesn't belong to any namespace.
Log:
```
2015-04-30 16:02:56,948: ERROR – System.ArgumentException: String cannot be of zero length.
Parameter name: oldValue
   at System.String.ReplaceInternal(String oldValue, String newValue)
   at System.String.Replace(String oldValue, String newValue)
   at SharpDox.Build.NRefactory.Parser.NamespaceParser.GetParsedNamespace(IType type)
   at SharpDox.Build.NRefactory.Parser.NamespaceParser.ParseProjectNamespaces(CSharpProject project)
   at SharpDox.Build.NRefactory.NRefactoryParser.ParseNamespaces(CSharpSolution solution, SDRepository sdRepository, ICoreConfigSection sharpDoxConfig, Dictionary`2 tokens)
   at SharpDox.Build.NRefactory.NRefactoryParser.GetFullParsedSolution(String solutionFile, ICoreConfigSection sharpDoxConfig, Dictionary`2 tokens)
   at SharpDox.Build.Context.Step.ParseCodeStep.RunStep(SDProject sdProject)
   at SharpDox.Build.Context.BuildContext.StartBuild()
```

**Comment by Geaz** [comment]
Added a fix for this in the dev branch.
Thank you for the report!
