### ISSUE TITLE
WPF with .NET 4.0 generates IndexOutOfRangeException

### ISSUE THREAD

**Issue by UbbeLoL** [Geaz/sharpDox#62]
It seems that the GUI application fails to parse WPF projects.  

Here is the output when attempting to parse it:

```
Starting step: "Parsing project file"
Starting step: "Parsing code"
Could not build documentation.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at SharpDox.Build.Roslyn.Parser.ProjectParser.SeeParser.ResolveAllSeeTokens()
   at SharpDox.Build.Roslyn.RoslynParser.ResolveSeeTokens(ParserOptions parserOptions)
   at SharpDox.Build.Roslyn.RoslynParser.GetParsedSolution(String solutionFile, ICoreConfigSection sharpDoxConfig, Dictionary`2 tokens, Boolean parseMethodCalls)
   at SharpDox.Build.Context.Step.StructeParseCodeStep.RunStep(SDProject sdProject)
   at SharpDox.Build.Context.BuildContext.StartBuild()
```

**Comment by Geaz** [comment]
This seems to be a problem with empty see tags. Could you please test the following build (just extract into your current sharpdox Folder)? Thank you!

https://ci.appveyor.com/api/buildjobs/x1mikpti525dyley/artifacts/build.zip

**Comment by drusa** [comment]
It is much the same error in this "following" build than it was in 1.1.1. There were already some bugs in [previous one](https://github.com/Geaz/sharpDox/issues/56) as well, sorry, I became very nervous so it's high time to find better opportunity. Good luck!

**Comment by Geaz** [comment]
Thanks for the comment. I am very sorry to hear this, as you can see I am always very curious to fix any issue (mainly I respond to issues in less a day).

Will close this one, as it seems that I won't get any more input to this issue.

**Comment by Geaz** [comment]
#64 related - possible solution there
