### ISSUE TITLE
InvalidOperationException when parsing references .NET Framework 4.6

### ISSUE THREAD

**Issue by MrDark** [Geaz/sharpDox#65]
I'm getting the following error when parsing our solution.
```
Starting step: "Parsing project file"
Starting step: "Parsing code"
Could not build documentation.
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at SharpDox.Build.Roslyn.Parser.ProjectParser.SeeParser.ResolveAllSeeTokens()
   at SharpDox.Build.Roslyn.RoslynParser.ResolveSeeTokens(ParserOptions parserOptions)
   at SharpDox.Build.Roslyn.RoslynParser.GetParsedSolution(String solutionFile, ICoreConfigSection sharpDoxConfig, Dictionary`2 tokens, Boolean parseMethodCalls)
   at SharpDox.Build.Context.Step.ParseCodeStep.RunStep(SDProject sdProject)
   at SharpDox.Build.Context.BuildContext.StartBuild()
```

After some investigation I managed to reproduce it with the following class in an empty .NET 4.6 project/solution.

```
    public class TestClass
    {
        public enum MyEnum
        {
        }

        public List<MyEnum> GetListOfEnum()
        {
            return new List<MyEnum>();
        }

        public List<int> GetListOfInts()
        {
            return new List<int>();
        }
    }
```

Update: It would be nice if the error dialog shows which file/project it was parsing so it's easier to pin-point the problem.

**Comment by MrDark** [comment]
Might have found a possible solution see #66 

After this fix I was able to generate documentation for our solution.

**Comment by Geaz** [comment]
Thank you for the contribution! I will look into this on friday (as soon as I am back from vacation).
Am 06.07.2016 15:59 schrieb Danny <notifications@github.com>:Might have found a possible solution see #66 

After this fix I was able to generate documentation for our solution.

**Comment by Geaz** [comment]
I tried to reproduce this error, but it was successfully running with the above class in an empty project.
Could you please attach your test project? Then I could try to reproduce it again. Thank you very much!

**Comment by Geaz** [comment]
Closing due to inactivity. Will reopen it, if there is more input in the future.
