### ISSUE TITLE
Could not build documentation

### ISSUE THREAD

**Issue by starkskalle** [Geaz/sharpDox#72]
Hi,

I am not entirely sure if my .sdnav file is correct so I am attaching it as well (I have changed the file extension to .txt). I am having the same issue in two latest versions (1.2.0 and 1.1.2):

```
Starting step: "Parsing project file"
Starting step: "Parsing code"
Starting step: "Export documentation"
Could not build documentation.
System.NullReferenceException: Object reference not set to an instance of an object.
   at SharpDox.Plugins.Html.Templates.Navigation.Navigation.TransformText()
   at SharpDox.Plugins.Html.Steps.CreateDataStep.CreateNavigationData()
   at SharpDox.Plugins.Html.Steps.CreateDataStep.RunStep()
   at SharpDox.Plugins.Html.HtmlExporter.Export(SDProject sdProject, String outputPath)
   at SharpDox.Build.Context.Step.ExportStep.RunAllExporters(SDProject sdProject)
   at SharpDox.Build.Context.Step.ExportStep.RunStep(SDProject sdProject)
   at SharpDox.Build.Context.BuildContext.StartBuild()
```
[doc-nav.txt](https://github.com/Geaz/sharpDox/files/544293/doc-nav.txt)

Let me know if there is anything else you need to investigate this potential issue.

Thanks

**Comment by starkskalle** [comment]
It looks like the issue above was caused be the fact that my navigation file name was NOT default.sdnav.

**Comment by Geaz** [comment]
Will add a better error message for this case. Thank you for the Report!
