### ISSUE TITLE
Unable to build doc

### ISSUE THREAD

**Issue by carldebilly** [Geaz/sharpDox#75]
On first try of the tool, I'm getting an error while trying to generate a documentation from a .sln file :
```
Starting step: "Parsing project file"
Starting step: "Parsing code"
Could not build documentation.
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at SharpDox.Build.Roslyn.Parser.ProjectParser.SeeParser.ResolveAllSeeTokens()
   at SharpDox.Build.Roslyn.RoslynParser.ResolveSeeTokens(ParserOptions parserOptions)
   at SharpDox.Build.Roslyn.RoslynParser.GetParsedSolution(String solutionFile, ICoreConfigSection sharpDoxConfig, Dictionary`2 tokens, Boolean parseMethodCalls, Boolean ignoreExcludes)
   at SharpDox.Build.Context.Step.ParseCodeStep.RunStep(SDProject sdProject)
   at SharpDox.Build.Context.BuildContext.StartBuild()
```
On the main window, there's an error message in red saying : `Parsing References: .NET Framework 4.5`

You have to know it's a big solution, with a 107 projets and includes those technologies :
 * .NET 4.5 / .NET 4.5.1 / .NET 4.6 / WPF & MS Unit tests projects
 * Windows Universal (UWP)
 * Xamarin iOS
 * Xamarin Android
 * Windows Phone 8.1 "Silverlight"
 * Windows Phone 8.1 "Jupiter"
 * Windows 8.1 "WinRT"
 * Silverlight 5
 * A lot of shared projects for multitargetting code among all previous targets
 * A lot of output targets

Could the problem be related to the complexity of our solution ?

**Comment by Geaz** [comment]
There was already a similar Problem with sharpDox before. Today I merged a pull request regarding this issue and released a new Version. Could you please check, if this solved your issue? Thank you! (New Version: https://github.com/Geaz/sharpDox/releases/download/v1.2.1/sharpDox.1.2.1.zip)

**Comment by carldebilly** [comment]
Negative.  I just proposed a new PR to fix the remaining bugs.

**Comment by Geaz** [comment]
Merged and closed
