### ISSUE TITLE
Error while generating documents

### ISSUE THREAD

**Issue by rishabh456** [geaz/sharpDox#92]
I am getting below error while generating documents. Can some one please help to resolve this. I am using VS2015 on my machine.

**Error Details:**  

Starting step: "Parsing project file"
Starting step: "Parsing code"
Could not build documentation.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<WithAssemblies>b__0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
   at Microsoft.CodeAnalysis.Host.Mef.DesktopMefHostServices.get_DefaultServices()
   at Microsoft.CodeAnalysis.MSBuild.MSBuildWorkspace.Create()
   at SharpDox.Build.Roslyn.RoslynLoader.LoadSolutionFile(String solutionFile) in C:\Users\mehtar2\Downloads\Temp\sharpDox-dev\src\Libraries\SharpDox.Build.Roslyn\RoslynLoader.cs:line 11
   at SharpDox.Build.Roslyn.RoslynParser.GetParsedSolution(String solutionFile, ICoreConfigSection sharpDoxConfig, Dictionary`2 tokens, Boolean parseMethodCalls, Boolean ignoreExcludes) in C:\Users\mehtar2\Downloads\Temp\sharpDox-dev\src\Libraries\SharpDox.Build.Roslyn\RoslynParser.cs:line 35
   at SharpDox.Build.Context.Step.ParseCodeStep.RunStep(SDProject sdProject) in C:\Users\mehtar2\Downloads\Temp\sharpDox-dev\src\Libraries\SharpDox.Build\Context\Step\ParseCodeStep.cs:line 20
   at SharpDox.Build.Context.BuildContext.StartBuild() in C:\Users\mehtar2\Downloads\Temp\sharpDox-dev\src\Libraries\SharpDox.Build\Context\BuildContext.cs:line 42

**Comment by geaz** [comment]
Hi, what version of sharpDox do you use? Latest release?

**Comment by rishabh456** [comment]
I am using sharpDox-Dev Version 1.2.2

**Comment by rishabh456** [comment]
I tried sharpDox Version 1.2.1 and i am now getting successful build but in the output folder there are no documents getting generated. I have notice that "Exporters" dropdown contain no options. See attached image for reference.
![image](https://user-images.githubusercontent.com/32763532/31668689-869da07e-b370-11e7-8ebb-a09bc52ae4db.png)

**Comment by geaz** [comment]
The exporters are own projects. I think you don't have any exporter plugin in your plugin folder.
Please take the "official" release from the homepage (http://sharpdox.de), extract it and copy the "plugins" folder to your sharpDox folder. Then you should see the html exporter.

**Comment by geaz** [comment]
Closed, because no more activity on this issue.
